/// <reference path="../pb_data/types.d.ts" />
onRecordAfterCreateSuccess((e) => {
    // This hook sends an OTP email when a password reset is requested
    // The OTP code is generated by PocketBase and sent automatically
    const userEmail = e.record.get("email");

    if (!userEmail) {
        e.next();
        return;
    }

    // Send OTP email notification
    const message = new MailerMessage({
        from: {
            address: $app.settings().meta.senderAddress,
            name: $app.settings().meta.senderName
        },
        to: [{ address: userEmail }],
        subject: "Password Reset - Your OTP Code",
        html: "<h2>Password Reset Request</h2><p>We received a request to reset your password. Use the OTP code sent to your email to proceed with the password reset.</p><p>If you did not request this, please ignore this email.</p><p>Your OTP code is valid for 5 minutes.</p>"
    });

    try {
        $app.newMailClient().send(message);
    } catch (err) {
        console.log("Failed to send OTP email: " + err.message);
    }

    e.next();
}, "users");